### PR TITLE
Validate all UI input on CodeGenerationParameterValidationStep

### PR DESCRIPTION
**Pull request by Florian-Schoenherr**
...`Data` classes check all input from UI directly after receiving for `null`, only deployment and persistence are special cases.
The validation step checks via regex and some enums if the values are correct.
This could be expanded, some messages are not too specific.
Maybe we could do some tests. There is also one TODO, didn't know how to do that / if it's needed.
@danilo-ambrosio

### CODE REVIEW

**Comment by Florian-Schoenherr** [comment]
What does DCO want from me?

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr Please see this thread. Also explained on team Slack workspace.

https://twitter.com/vlingo_io/status/1329148542422683650

**Comment by danilo-ambrosio** [comment]
Well done @Florian-Schoenherr ! Your implementation will considerably protect `starter` from invalid / inconsistent data.
From my side, the review status is approved. Will you handle the DCO item? 
If you get a chance, later on please add tests for the validation cases.

**Comment by VaughnVernon** [comment]
Thanks, @danilo-ambrosio! @Florian-Schoenherr Please consider tests your top priority along with updated screen captures in docs.

**Comment by Florian-Schoenherr** [comment]
I already did the DCO stuff, I think your merge replanted my unsigned commits.. should I do it again?

**Comment by VaughnVernon** [comment]
Perhaps so, sorry. It's the same agreement so signing multiple times makes no difference and gets this done.

**Comment by Florian-Schoenherr** [comment]
There are some really old commits, on my end git doesn't go back there because of performance - node_modules is getting crawled by git... can someone try on their end? You just have to do what DCO `Details` says.

**Comment by Florian-Schoenherr** [comment]
I got it done using `git rebase -i e2650da^`.

**Comment by Florian-Schoenherr** [comment]
Now it found new commit which aren't signed-off again. I don't like this. Can we just use DCO after this?
I configured my commits to auto sign-off now, @danilo-ambrosio you should do so too, probably.

**Comment by Florian-Schoenherr** [comment]
Ok, this time it worked.

**Comment by Florian-Schoenherr** [comment]
Is this test enough? We could add more obscure input values or have some "wrong value" tests.

**Pull request merged**
