### PR TITLE
Migrate UI from angular to svelte (sapper)

### PR DESCRIPTION
**Pull request by Florian-Schoenherr**
This is a lot lighter then the angular code, if there is something missing, please tell me.
If you need help with understanding the svelte code, I can help too.
E2E-tests are not available, but probably a good idea.
Component library used is svelte-materialify.

This works like schemata - you can build:
 `mvn clean package -Pfrontend`
and run:
`java -jar target/vlingo-xoom-starter-1.4.1-SNAPSHOT.jar gui`

### CODE REVIEW

**Comment by Florian-Schoenherr** [comment]
What should we put on `Home` (`/`)?
If we don't want a `Home`page I think we need index.html to be served by default, not only on `/` but also the respective index.html on `/context/` and `/context`.
I could also redirect on Home to `/context` and keep it empty and delete it from navbar.

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr All `/` and `.../` as well as `/pathend` must have a corresponding `index.html` to serve.

I don't understand your point about Home and Context. If you mean that they are one and the same, then opt for Context over Home because Context has clear meaning. I don't remember having Home there originally.

I know this is a bit of a sidebar, but the following names have bothered me a bit, and I think they should be changed to what follows.

From: `Model - Aggregates` To: `Model`

From: `Model - Persistence` To: `Persistence`

Isn't that better?

**Comment by Florian-Schoenherr** [comment]
@VaughnVernon 

> names have bothered me

me too, have already changed that.
I would delete Home but `/context` doesn't serve `/context/index.html`. It only works on `/`, which serves `/index.html`.

**Comment by VaughnVernon** [comment]
> Could you add that to VLINGO/HTTP?

I thought I did. That's why `/` which serves `/index.html`. Would you please set a breakpoint in `io.vlingo.http.resource.StaticFilesResource::serveFile()` and find out why it's not working for `/context`?

**Comment by Florian-Schoenherr** [comment]
@VaughnVernon it seems breakpoints don't work there, but what I found out is when I reload a page, now it downloads this:
on aggregates
"Datei" means file.

**Comment by Florian-Schoenherr** [comment]
`StaticFilesResource.contentFilePath() -> maybeContent.isDirectory()` is `false` when requesting `/context`, so it doesn't add `index.html` to the end. `path` is `/frontend/context` in that moment.

**Comment by VaughnVernon** [comment]
Perhaps we need to try both `path` and `"." + path` for absolute and relative.

**Comment by danilo-ambrosio** [comment]
@Florian-Schoenherr 
Finally made the review. I got really impressed with the new UI using Svelte. Such fantastic work! Congrats!
The only comment I have is about the route path: 
image

Sometimes users may leave it blank meaning that the route path is the same as the root. This is the only adjustment I found.

**Comment by Florian-Schoenherr** [comment]
I think you can't add the aggregate if the route path is empty

**Comment by danilo-ambrosio** [comment]
The adjustment is to make this field optional. Actually, the path field is always relative to the root path, for instance:
- If the root path is **/accounts** and the relative route path is **/balance**, the project generator resolves the path as **/accounts/balance**
- If the root path is **/accounts** and the relative route path is blank, the project generate resolves the route path as **/accounts**

Is it understandable? If you prefer, you can even change the field name to **Relative Path**

**Comment by Florian-Schoenherr** [comment]
Resolved this on Slack, users can use root="/something" path="/".

**Comment by danilo-ambrosio** [comment]
Totally agree. Just tested here and it works.

**Review by rsaraphael — APPROVED** [review]

**Comment by donnisnoni** [comment]
Can I join the slack channel @VaughnVernon ?

**Pull request merged**
