### PR TITLE
Improvements/value object

### PR DESCRIPTION
**Pull request by abdullahcalisir12**
fixes for #30

### CODE REVIEW

**Comment by danilo-ambrosio** [comment]
@abdullahcalisir12 
I will validate your PR in a moment.  Meanwhile, could you please ensure that the value object node in the generation settings json schema is shaped as in the following image?

vo-schema

Please let me know if you have any questions about this schema.

Thanks in advance!

**Comment by Florian-Schoenherr** [comment]
@danilo-ambrosio the schema also shows it pretty well, VO should be another page besides aggregate 😉

**Comment by abdullahcalisir12** [comment]
@danilo-ambrosio currently valueObjectSettings doesn't look like in the json you sent above, but I will make it look like so soon.

**Comment by abdullahcalisir12** [comment]
@danilo-ambrosio I updated PR according to JSON schema you provided for `valueObjectSettings`.

**Comment by VaughnVernon** [comment]
@danilo-ambrosio Please see my comment in #30 about the new VO dialog. Also please review on my behalf and approve when ready.

**Comment by Florian-Schoenherr** [comment]
If I understood right, there's a new Value-Object Page, which has the same setup as the Aggregate page, so you press "new" and open a Dialog with it. The Aggregate-Dialog either links you there or also opens the Dialog (via "New Value-Object"-Button or something along those lines)? Basically what we want is a way for people who have already filled out some stuff on Aggregate-Dialog to then be able to add Value-Objects without losing their progress?

**Comment by VaughnVernon** [comment]
@Florian-Schoenherr @abdullahcalisir12 The thing is, this is not data entry, which seems to be the thought process here. You don't mechanically enter Value Objects and then Aggregate as if everything is all perfectly planned out before and how you are just using this UI instead of an IDE. Instead, you think of an Aggregate as a top level concept in the Model and as you define it you are discussing with your team how it should work. You and your team realize that you need a new type, which will be a Value Object. So you define that Value Object type and then use it as the field type in the Aggregate.

Think of how you actually write code. It's not mechanical. It's creative.

**Comment by abdullahcalisir12** [comment]
@VaughnVernon @Florian-Schoenherr @danilo-ambrosio you can review UI here https://vlingo-xoom-starter.vercel.app/aggregates

**Pull request merged**
